### ISSUE TITLE
Master shutdown

### ISSUE THREAD

**Issue by MillenniumForce** [MillenniumForce/overkill#8]
- [x] Send notification to workers that Master has shutdown
- [x] Worker should respond by setting `_master = None`

### Error

From worker:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/juliangarratt/Desktop/overkill/overkill/servers/worker.py", line 56, in stop
    close_connection_with_master()
  File "/Users/juliangarratt/Desktop/overkill/overkill/servers/_worker.py", line 115, in close_connection_with_master
    send_message(msg, _master.address)
  File "/Users/juliangarratt/Desktop/overkill/overkill/servers/_utils.py", line 25, in send_message
    s.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

Due to:
https://github.com/MillenniumForce/overkill/blob/f24fa49463d85c961a72bfc9b768bb5730136c2f/overkill/servers/_worker.py#L113-L115

**Comment by MillenniumForce** [comment]
Changed fix: if the worker faces some issue sending a closing message to the master, then just log the issue. Most likely case is that the master is not online. If the master is online and the closing message cannot be send then there is probably some deeper issue/bug.
